### ISSUE TITLE
NodeJS 10: no equals method in array prototype

### ISSUE THREAD

**Issue by AndreyMiloserdov** [medooze/semantic-sdp-js#15]
/experiments/node-media-test/node_modules/semantic-sdp/lib/SDPInfo.js:312
                        if (this.candidates[i].equals(candidate))
                                               ^

TypeError: this.candidates[i].equals is not a function
    at SDPInfo.addCandidate (/experiments/node-media-test/node_modules/semantic-sdp/lib/SDPInfo.js:312:27)
    at SDPInfo.addCandidates (/experiments/node-media-test/node_modules/semantic-sdp/lib/SDPInfo.js:328:9)

**Comment by murillo128** [comment]
can you check what is the value of the `this.candidates[i]` ?
