### ISSUE TITLE
Posible regression

### ISSUE THREAD

**Issue by netizen-ais** [medooze/semantic-sdp-js#34]
This happens on Node v21.1.0 with module version 3.26.10, but works ok in 3.26.6 (Node v.20.9.0)

```
throw new Error(`invalid integer ${xStr}`);
^

Error: invalid integer add
at strictParseInt (/home/parejasdating/dev/node_modules/semantic-sdp/dist/MediaInfo.js:541:15)
at MediaInfo.expand (/home/parejasdating/dev/node_modules/semantic-sdp/dist/MediaInfo.js:510:32)
at SDPInfo.expand (/home/parejasdating/dev/node_modules/semantic-sdp/dist/SDPInfo.js:1027:37)
at Namespace.<anonymous> (/home/parejasdating/dev/node_modules/medooze-media-server/lib/PeerConnectionServer.js:52:26)
at Namespace.emit (node:events:515:28)
at TransactionManager.listener (/home/parejasdating/dev/node_modules/transaction-manager/index.js:246:18)
```

**Comment by mildsunrise** [comment]
`extensions` is expected to contain integer keys, i.e.

~~~ json
      "extensions": {
        "2": "urn:ietf:params:rtp-hdrext:toffset",
        "3": "http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/abs-send-time",
        "4": "urn:3gpp:video-orientation",
        "5": "http:\/\/www.ietf.org\/id\/draft-holmer-rmcat-transport-wide-cc-extensions-01",
        "6": "http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/playout-delay"
      },
~~~

but for some reason, the `create` command sent to the PeerConnectionServer has an `add` extension key. I'm not familiar with PeerConnectionServer but this is a bug that should be fixed there, unless i'm missing something.

**Comment by netizen-ais** [comment]
In my code (is now working live under node 21 with this module at 3.26.6:
```
				tm = new TransactionManager(wsProxy);
				pc = this.mediaServer.createPeerConnectionServer(tm, capabilities);

```
where capabilites is the result of [MediaServer.getDefaultCapabilities](https://github.com/medooze/media-server-node/blob/499c3b59b9e7822b7a5c2a3ccaa1be71954db53a/lib/MediaServer.js#L330) which returns extensions as an array:

```
			extensions	: [
				"urn:3gpp:video-orientation",
				"http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
				"urn:ietf:params:rtp-hdrext:sdes:mid",
				"urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id",
				"urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id",
				"http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time"
			]

```

I've just checked and it breaks at revision 3.26.7

**Comment by mildsunrise** [comment]
that code is fine, `capabilities` should only contain the URIs. the problem is at the other end, which sends a `create` command with an invalid offer

**Comment by mildsunrise** [comment]
(and yes, I'm aware that this error was introduced with the recent 3.26.something release, it is because we're now validating that keys are a number whereas we previously didn't bother to check, resulting in a NaN parsed key)

**Comment by murillo128** [comment]
@netizen-ais Can you check the value of the create message sent over websocket?
![image](https://github.com/medooze/semantic-sdp-js/assets/1070835/0d4ecc96-8e1b-4f00-86a1-c592b79cd15e)

**Comment by netizen-ais** [comment]
This is the working create frame data:

```
{
    "version": 0,
    "streams": [
        {
            "id": "-",
            "tracks": [
                {
                    "media": "audio",
                    "id": "09503c1f-9547-4251-83c5-29352a6c6096",
                    "ssrcs": [
                        2487355741
                    ],
                    "mediaId": "0"
                },
                {
                    "media": "video",
                    "id": "58505d5e-069b-4590-89e5-6e791b0b3445",
                    "ssrcs": [
                        194712135,
                        591857800
                    ],
                    "mediaId": "1",
                    "groups": [
                        {
                            "semantics": "FID",
                            "ssrcs": [
                                194712135,
                                591857800
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    "medias": [
        {
            "id": "0",
            "type": "audio",
            "direction": "sendonly",
            "codecs": [
                {
                    "codec": "opus",
                    "type": 111,
                    "channels": 2,
                    "params": {
                        "minptime": "10",
                        "useinbandfec": "1"
                    },
                    "rtcpfbs": [
                        {
                            "id": "transport-cc"
                        }
                    ]
                },
                {
                    "codec": "G722",
                    "type": 9
                },
                {
                    "codec": "PCMU",
                    "type": 0
                },
                {
                    "codec": "PCMA",
                    "type": 8
                },
                {
                    "codec": "CN",
                    "type": 13
                },
                {
                    "codec": "telephone-event",
                    "type": 110
                },
                {
                    "codec": "telephone-event",
                    "type": 126
                }
            ],
            "extensions": {
                "1": "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
                "2": "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
                "3": "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
                "4": "urn:ietf:params:rtp-hdrext:sdes:mid"
            }
        },
        {
            "id": "1",
            "type": "video",
            "direction": "sendonly",
            "codecs": [
                {
                    "codec": "VP8",
                    "type": 96,
                    "rtx": 97,
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "H264",
                    "type": 102,
                    "rtx": 103,
                    "params": {
                        "level-asymmetry-allowed": "1",
                        "packetization-mode": "1",
                        "profile-level-id": "42001f"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "H264",
                    "type": 104,
                    "rtx": 105,
                    "params": {
                        "level-asymmetry-allowed": "1",
                        "packetization-mode": "0",
                        "profile-level-id": "42001f"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "H264",
                    "type": 106,
                    "rtx": 107,
                    "params": {
                        "level-asymmetry-allowed": "1",
                        "packetization-mode": "1",
                        "profile-level-id": "42e01f"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "H264",
                    "type": 108,
                    "rtx": 109,
                    "params": {
                        "level-asymmetry-allowed": "1",
                        "packetization-mode": "0",
                        "profile-level-id": "42e01f"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "H264",
                    "type": 127,
                    "rtx": 125,
                    "params": {
                        "level-asymmetry-allowed": "1",
                        "packetization-mode": "1",
                        "profile-level-id": "4d001f"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "H264",
                    "type": 39,
                    "rtx": 40,
                    "params": {
                        "level-asymmetry-allowed": "1",
                        "packetization-mode": "0",
                        "profile-level-id": "4d001f"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "AV1",
                    "type": 45,
                    "rtx": 46,
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "VP9",
                    "type": 98,
                    "rtx": 99,
                    "params": {
                        "profile-id": "0"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                },
                {
                    "codec": "VP9",
                    "type": 100,
                    "rtx": 101,
                    "params": {
                        "profile-id": "2"
                    },
                    "rtcpfbs": [
                        {
                            "id": "goog-remb"
                        },
                        {
                            "id": "transport-cc"
                        },
                        {
                            "id": "ccm",
                            "params": [
                                "fir"
                            ]
                        },
                        {
                            "id": "nack"
                        },
                        {
                            "id": "nack",
                            "params": [
                                "pli"
                            ]
                        }
                    ]
                }
            ],
            "extensions": {
                "2": "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
                "3": "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
                "4": "urn:ietf:params:rtp-hdrext:sdes:mid",
                "5": "http://www.webrtc.org/experiments/rtp-hdrext/playout-delay",
                "6": "http://www.webrtc.org/experiments/rtp-hdrext/video-content-type",
                "7": "http://www.webrtc.org/experiments/rtp-hdrext/video-timing",
                "8": "http://www.webrtc.org/experiments/rtp-hdrext/color-space",
                "10": "urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id",
                "11": "urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id",
                "13": "urn:3gpp:video-orientation",
                "14": "urn:ietf:params:rtp-hdrext:toffset"
            }
        }
    ],
    "candidates": [],
    "ice": {
        "ufrag": "BGv1",
        "pwd": "8vOFqKPLxhE4fRj86Bd13tKc"
    },
    "dtls": {
        "setup": "actpass",
        "hash": "sha-256",
        "fingerprint": "4B:FD:BE:C5:B3:E2:4D:92:A2:6D:EB:BA:C4:94:4F:1C:3D:E9:2D:47:6F:7F:53:8B:7B:AB:FE:66:A8:0C:9B:65"
    }
}

```

**Comment by netizen-ais** [comment]
I've checked the data against a failed attempt to 3.26.7 and it seems identical. The extensions format is the same, an Object with numerical keys

![image](https://github.com/medooze/semantic-sdp-js/assets/3426685/e3e84fbb-f138-4270-ac70-e87e4aeeb1e6)

**Comment by murillo128** [comment]
I think this should fix it

**Comment by netizen-ais** [comment]
Now crashes later:

```
/home/parejasdating/dev/node_modules/medooze-media-server/node_modules/semantic-sdp/dist/CodecInfo.js:219
for (const rtcpfb of plain.rtcpfbs) {
^

TypeError: plain.rtcpfbs is not iterable
at CodecInfo.expand (/home/parejasdating/dev/node_modules/medooze-media-server/node_modules/semantic-sdp/dist/CodecInfo.js:219:32)
at MediaInfo.expand (/home/parejasdating/dev/node_modules/medooze-media-server/node_modules/semantic-sdp/dist/MediaInfo.js:514:37)
at SDPInfo.expand (/home/parejasdating/dev/node_modules/medooze-media-server/node_modules/semantic-sdp/dist/SDPInfo.js:1027:37)
at Namespace.<anonymous> (/home/parejasdating/dev/node_modules/medooze-media-server/lib/PeerConnectionServer.js:52:26)
```

**Comment by netizen-ais** [comment]
I managed to get it working, I'll submit a PR, but please review carefully as I don't really understand the internals

**Comment by netizen-ais** [comment]
#36

**Comment by mildsunrise** [comment]
i was not able to reproduce your original error with the data you sent https://github.com/medooze/semantic-sdp-js/issues/34#issuecomment-1781116530 on version 3.26.7, and with Node v21.1.0:

~~~
$ npm i semantic-sdp@3.26.7

added 5 packages in 6s

1 package is looking for funding
  run `npm fund` for details

$ node
Welcome to Node.js v21.1.0.
Type ".help" for more information.
> require("semantic-sdp").SDPInfo.expand(require("./data.json"))
Uncaught TypeError: plain.rtcpfbs is not iterable
    at CodecInfo.expand (/tmp/node_modules/semantic-sdp/dist/CodecInfo.js:219:32)
    at MediaInfo.expand (/tmp/node_modules/semantic-sdp/dist/MediaInfo.js:514:37)
    at SDPInfo.expand (/tmp/node_modules/semantic-sdp/dist/SDPInfo.js:1027:37)
~~~

so, something is off here. if sergio's commit "fixed" your problem, maybe there's some kind of prototype pollution? please place a `console.log(Object.prototype)` just before the call to SDPInfo.expand() in PeerConnectionServer.js.

**Comment by netizen-ais** [comment]
This (and another similar) error is what I managed to bypass (dirty fix) in my PR, but if you try the same against prior release, you'll see it works

**Comment by mildsunrise** [comment]
> This (and another similar) error is what I managed to bypass (dirty fix) in my PR

i know, this is not what i'm talking about. i'm talking about your previous error, the `Error: invalid integer add` one. even if Sergio's commit "fixed" it, i'd still like to find out what was causing it, that's why it would be nice to see the output of the console.log statement I posted

**Comment by netizen-ais** [comment]
```
ws2:~$ npm i semantic-sdp@3.26.6

changed 1 package, and audited 6 packages in 399ms

1 package is looking for funding
run `npm fund` for details

found 0 vulnerabilities
ws2:~$ node
Welcome to Node.js v21.1.0.
Type ".help" for more information.
> require('semantic-sdp').SDPInfo.expand(require('./sdp.json'));
SDPInfo {
    version: 1,
    streams: Map(1) { '-' => StreamInfo { id: '-', tracks: [Map] } },
    medias: [
        MediaInfo {
            id: '0', ...
```

**Comment by mildsunrise** [comment]
ah, i was referring to the

> please place a `console.log(Object.prototype)` just before the line that calls `SDPInfo.expand()` in `/home/parejasdating/dev/node_modules/medooze-media-server/lib/PeerConnectionServer.js`

**Comment by netizen-ais** [comment]
Nice catch, it seems some module added a json method to the prototype. I'll dig into it tomorrow.

Thank you

**Comment by mildsunrise** [comment]
that explains it then. even if the module is indeed augmenting Object.prototype with some method in good faith (even though it is extremely discouraged) it should add a non-enumerable property as to not interfere with any library which may use for..in, like us

**Comment by netizen-ais** [comment]
You wouldn't believe this but I'll have real Halloween nightmares because that code not only was adding a json method in Object.prototype, it also defines the same method in String.prototype so instead of using JSON.parse / JSON.stringify it uses Variable.json() to convert between them, so reading that code is extremely difficult as an action and its opposite are the very same code!
