### ISSUE TITLE
TypeError: Cannot read property 'application' of undefined

### ISSUE THREAD

**Issue by reklatsmasters** [medooze/semantic-sdp-js#6]
I'm trying to make sdp answer for this offer:

```js
const iceinfo = new sdp.ICEInfo(createUsername(), createPassword());
const dtlsinfo = new sdp.DTLSInfo(ACTIVE, 'sha-1', CERT_SHA1_FINGERPRINT);

console.log(
  'chrome',
  sdp.SDPInfo.parse(offer).answer({ ice: iceinfo, dtls: dtlsinfo })
);
```

```
v=0
o=- 5636137646675714991 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE data
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:8qF7
a=ice-pwd:zjQd1U0/CufgXINHcPcdd0Bd
a=ice-options:trickle
a=fingerprint:sha-256 10:8E:F5:D7:A2:B3:63:EF:BD:64:8C:5F:56:A0:66:05:9F:B1:5C:1A:C5:79:BD:EE:90:92:C4:1A:C4:B7:1F:58
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
```

Hovewer, i've got error

```
/home/dtsvet/develop/projects/xxx/node_modules/semantic-sdp/lib/SDPInfo.js:403
			const supported = params && params.capabilities[media.getType()];
			                                               ^

TypeError: Cannot read property 'application' of undefined
    at SDPInfo.answer (/home/dtsvet/develop/projects/xxx/node_modules/semantic-sdp/lib/SDPInfo.js:403:51)
    at Object.<anonymous> (/home/dtsvet/develop/projects/xxx/test.js:62:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

**Comment by notedit** [comment]
@reklatsmasters   semantic-sdp-js  does not support  Datachannel  now

**Comment by murillo128** [comment]
yes, DataChannels  is not supported, but it shouldn't break
